version: '3'
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  redis:
    image: redis
    ports:
      - "6379:6379"
