name: Server tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      test_db:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_database
        ports:
          - 5433:5432
        options: >-
            --health-cmd pg_isready 
            --health-interval 10s 
            --health-timeout 5s 
            --health-retries 5
      test_redis:
        image: redis
        ports:
          - 6380:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v3.5.2
      
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.0.0

      - name: Install Dependencies
        run: yarn install
        working-directory: ./server

      - name: Run Tests
        run: yarn test:ci
        working-directory: ./server
        env:
          NODE_ENV: test
          REDIS_HOST: localhost
          REDIS_PORT: 6380
          DATABASE_HOST: localhost
          DATABASE_PORT: 5433
          DATABASE_USER: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_NAME: test_database
